en:
   languageCode: en-us
   languageName: "English"
   contentDir: content/en
   weight: 1
   
ru:
   languageCode: "ru-ru"
   languageName: "Русский"
   contentDir: "content/ru"
   weight: 2
   menu:
     main:
       - name: Обо мне
         url: '#about'
         weight: 10
       - name: Посты
         url: '#posts'
         weight: 20
       - name: Проекты
         url: '#projects'
         weight: 30
       - name: Выступления
         url: '#talks'
         weight: 40
       - name: Публикации
         url: '#publication'
         weight: 50
       - name: Контакты
         url: '#contact'
         weight: 60
       - name: Биография
         url: '#biography'
         weight: 60
   
